name: GitHub Readme Stats Action
on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch: 

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate General Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.STATS_TOKEN }}
          card: overview
          path: generated/overview.svg
          options: theme=tokyonight&show_icons=true&count_private=true&hide_border=true

      - name: Generate Top Languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.STATS_TOKEN }}
          card: languages
          path: generated/languages.svg
          options: theme=tokyonight&hide_border=true&layout=compact&count_private=true
